// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tool.GenerateJava.GenerateModel
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class JavaEnumTemplate : JavaEnumTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n\t// this is a generated file from the \"Tool.GenerateJava\" project in .Net, plea" +
                    "se do not edit directly\r\n\r\npackage ");
            
            #line 13 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(package));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 15 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
 if (hasDescriptions) { 
            
            #line default
            #line hidden
            this.Write("\timport java.util.Arrays;\r\n\timport java.util.EnumSet;\r\n\r\n\timport com.google.gwt.u" +
                    "ser.client.ui.ListBox;\r\n\t");
            
            #line 20 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\r\nimport tickbox.web.shared.util.NullableEnum;\r\nimport com.google.gwt.user.c" +
                    "lient.Window;\r\n\r\npublic enum ");
            
            #line 27 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write(" {\r\n\t\r\n");
            
            #line 29 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"

	//Google(101, "Google Adwords"),
	//Bing(102, "Bing Ads");
	var index = 0;
	foreach(var d in enumValues) {
	
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 35 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(d.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 35 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(d.Value));
            
            #line default
            #line hidden
            
            #line 35 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(hasDescriptions ? string.Format(",\"{0}\"", d.Description.Replace("\"", "\\\"")) : ""));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 35 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumValues.Count -1 == index ? ";" : ","));
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 36 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"

	index++;
	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\r\n    private final int mVal;\r\n\t");
            
            #line 43 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
 if (hasDescriptions) { 
            
            #line default
            #line hidden
            this.Write("private final String mDescription;\r\n\t");
            
            #line 44 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n    private ");
            
            #line 46 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write("(int val");
            
            #line 46 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
 if (hasDescriptions) { 
            
            #line default
            #line hidden
            this.Write(", String description");
            
            #line 46 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(") {\r\n    \tmVal = val;\r\n    \t");
            
            #line 48 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
 if (hasDescriptions) { 
            
            #line default
            #line hidden
            this.Write("mDescription = description;\r\n");
            
            #line 49 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    }\r\n    \r\n    public int getValue() {\r\n    \treturn mVal;\r\n    }\r\n\t\r\n");
            
            #line 56 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
 if (hasDescriptions) { 
            
            #line default
            #line hidden
            this.Write("\tpublic String getDescription() {\r\n\t\treturn mDescription;\r\n\t}\r\n");
            
            #line 60 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\tpublic static ");
            
            #line 62 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write(" fromValue(int val) {\r\n\t\tfor (");
            
            #line 63 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write(" b : ");
            
            #line 63 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write(".values()) {\r\n\t\t\tif (val == b.mVal) {\r\n\t\t\t\treturn b;\r\n\t\t\t}\r\n\t\t}\r\n\t\tWindow.alert(\"" +
                    "Unknown ");
            
            #line 68 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write(": \" + String.valueOf(val));\r\n\t\treturn null;\r\n\t}\r\n\r\n\t\r\n\tpublic static NullableEnum" +
                    "<");
            
            #line 73 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write("> fromValue(String valStr) {\r\n\t\tif (\"\".equals(valStr) || \"0\".equals(valStr)) {\r\n\t" +
                    "\t\treturn new NullableEnum<");
            
            #line 75 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t}\r\n\t\tint val = Integer.parseInt(valStr);\r\n\t\tfor (");
            
            #line 78 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write(" b : ");
            
            #line 78 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write(".values()) {\r\n\t\t\tif (val == b.mVal) {\r\n\t\t\t\treturn new NullableEnum<");
            
            #line 80 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write(">(b);\r\n\t\t\t}\r\n\t\t}\r\n\t\tWindow.alert(\"Unknown ");
            
            #line 83 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write(": \" + String.valueOf(val));\r\n\t\treturn null;\r\n\t}\r\n\r\n\t");
            
            #line 87 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
 if (hasDescriptions) { 
            
            #line default
            #line hidden
            this.Write("\tpublic static void fillDropdown(ListBox target){\r\n\t\tfillDropdown(target, new ");
            
            #line 89 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write("[0]);\r\n\t}\r\n\r\n\tpublic static void fillDropdown(ListBox target, ");
            
            #line 92 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write("[] ignore){\r\n\t\t\r\n\t\tEnumSet<");
            
            #line 94 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write("> toIgnore = EnumSet.copyOf(Arrays.asList(ignore));\t\t\r\n\t\ttarget.clear();\r\n\t\tfor(");
            
            #line 96 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write(" v : ");
            
            #line 96 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumName));
            
            #line default
            #line hidden
            this.Write(".values()){\r\n\t\t\tif(!toIgnore.contains(v)){\t\t\t\t\r\n\t\t\t\ttarget.addItem(v.getDescripti" +
                    "on(), String.valueOf(v.getValue()));\r\n\t\t\t}\r\n\t\t}\r\n\t}\r\n\t");
            
            #line 102 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\Lat Projects\WL_Main\Tool.GenerateJava\GenerateModel\JavaEnumTemplate.tt"

private string _packageField;

/// <summary>
/// Access the package parameter of the template.
/// </summary>
private string package
{
    get
    {
        return this._packageField;
    }
}

private string _enumNameField;

/// <summary>
/// Access the enumName parameter of the template.
/// </summary>
private string enumName
{
    get
    {
        return this._enumNameField;
    }
}

private global::System.Collections.Generic.List<Tool.GenerateJava.GenerateModel.GenEnumItem> _enumValuesField;

/// <summary>
/// Access the enumValues parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<Tool.GenerateJava.GenerateModel.GenEnumItem> enumValues
{
    get
    {
        return this._enumValuesField;
    }
}

private bool _hasDescriptionsField;

/// <summary>
/// Access the hasDescriptions parameter of the template.
/// </summary>
private bool hasDescriptions
{
    get
    {
        return this._hasDescriptionsField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool packageValueAcquired = false;
if (this.Session.ContainsKey("package"))
{
    this._packageField = ((string)(this.Session["package"]));
    packageValueAcquired = true;
}
if ((packageValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("package");
    if ((data != null))
    {
        this._packageField = ((string)(data));
    }
}
bool enumNameValueAcquired = false;
if (this.Session.ContainsKey("enumName"))
{
    this._enumNameField = ((string)(this.Session["enumName"]));
    enumNameValueAcquired = true;
}
if ((enumNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("enumName");
    if ((data != null))
    {
        this._enumNameField = ((string)(data));
    }
}
bool enumValuesValueAcquired = false;
if (this.Session.ContainsKey("enumValues"))
{
    this._enumValuesField = ((global::System.Collections.Generic.List<Tool.GenerateJava.GenerateModel.GenEnumItem>)(this.Session["enumValues"]));
    enumValuesValueAcquired = true;
}
if ((enumValuesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("enumValues");
    if ((data != null))
    {
        this._enumValuesField = ((global::System.Collections.Generic.List<Tool.GenerateJava.GenerateModel.GenEnumItem>)(data));
    }
}
bool hasDescriptionsValueAcquired = false;
if (this.Session.ContainsKey("hasDescriptions"))
{
    this._hasDescriptionsField = ((bool)(this.Session["hasDescriptions"]));
    hasDescriptionsValueAcquired = true;
}
if ((hasDescriptionsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("hasDescriptions");
    if ((data != null))
    {
        this._hasDescriptionsField = ((bool)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class JavaEnumTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
