//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickbox.DatabaseApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterTemplate
    {
        public MasterTemplate()
        {
            this.Template = new HashSet<Template>();
        }
    
        public int MasterTemplateId { get; set; }
        public bool LockedTemplate { get; set; }
    
        public virtual ICollection<Template> Template { get; set; }
    }
}
