//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickbox.DatabaseApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public Node()
        {
            this.NodeSpecialism = new HashSet<NodeSpecialism>();
            this.TreeNode = new HashSet<TreeNode>();
        }
    
        public int NodeId { get; set; }
        public string NodeTitle { get; set; }
        public string NodeDesc { get; set; }
        public bool ChildrenMultiSelect { get; set; }
    
        public virtual ICollection<NodeSpecialism> NodeSpecialism { get; set; }
        public virtual ICollection<TreeNode> TreeNode { get; set; }
    }
}
