//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickbox.DatabaseApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodeSpecialism
    {
        public int NodeSpecialismId { get; set; }
        public int NodeId { get; set; }
        public int SpecialismId { get; set; }
        public int SequenceOrder { get; set; }
        public string Guidelines { get; set; }
        public string DocumentLink { get; set; }
    
        public virtual Node Node { get; set; }
        public virtual Specialism Specialism { get; set; }
    }
}
