//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickbox.DatabaseApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialism
    {
        public Specialism()
        {
            this.NodeSpecialism = new HashSet<NodeSpecialism>();
            this.Taxonomy = new HashSet<Taxonomy>();
        }
    
        public int SpecialismId { get; set; }
        public string SpecialismDesc { get; set; }
    
        public virtual ICollection<NodeSpecialism> NodeSpecialism { get; set; }
        public virtual ICollection<Taxonomy> Taxonomy { get; set; }
    }
}
