//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickbox.DatabaseApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxonomy
    {
        public Taxonomy()
        {
            this.TreeNode = new HashSet<TreeNode>();
            this.Specialism = new HashSet<Specialism>();
        }
    
        public int TaxonomyId { get; set; }
        public int TemplateId { get; set; }
        public string Title { get; set; }
        public bool IsScaffold { get; set; }
    
        public virtual Template Template { get; set; }
        public virtual ICollection<TreeNode> TreeNode { get; set; }
        public virtual ICollection<Specialism> Specialism { get; set; }
    }
}
