//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickbox.DatabaseApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TickboxDatabaseEntities : DbContext
    {
        public TickboxDatabaseEntities()
            : base("name=TickboxDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Node> Node { get; set; }
        public virtual DbSet<NodeSpecialism> NodeSpecialism { get; set; }
        public virtual DbSet<Specialism> Specialism { get; set; }
        public virtual DbSet<Taxonomy> Taxonomy { get; set; }
        public virtual DbSet<Template> Template { get; set; }
        public virtual DbSet<TreeNode> TreeNode { get; set; }
    }
}
