//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickbox.DatabaseApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeNode
    {
        public TreeNode()
        {
            this.TreeNode1 = new HashSet<TreeNode>();
        }
    
        public int TreeNodeId { get; set; }
        public int TaxonomyId { get; set; }
        public Nullable<int> ParentTreeNodeId { get; set; }
        public int NodeId { get; set; }
        public bool IsScaffold { get; set; }
    
        public virtual Node Node { get; set; }
        public virtual Taxonomy Taxonomy { get; set; }
        public virtual ICollection<TreeNode> TreeNode1 { get; set; }
        public virtual TreeNode TreeNode2 { get; set; }
    }
}
