//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behaviour in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
	//------------------------------------------------------------------------------

	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Diagnostics.CodeAnalysis;

	namespace TickBox.Data.Context
{
    [ExcludeFromCodeCoverage]
    public partial class Node
    {
    	public Node()
    	{
    	}
    
    	public virtual int NodeId { get; set; }
    	public virtual string NodeTitle { get; set; }
    	public virtual string NodeDesc { get; set; }
    	public virtual bool ChildrenMultiSelect { get; set; }
    
    	private IList<NodeSpecialism> nodeSpecialism;
    	public virtual IList<NodeSpecialism> NodeSpecialism 
    	{ 
    		get
    		{
    			if (this.nodeSpecialism == null)
    			{
    				this.nodeSpecialism = new List<NodeSpecialism>();
    			}
    
    			return this.nodeSpecialism;
    		}
    		
    		set
    		{
    			this.nodeSpecialism = value;
    		}
    	}
    	private IList<TreeNode> treeNodes;
    	public virtual IList<TreeNode> TreeNodes 
    	{ 
    		get
    		{
    			if (this.treeNodes == null)
    			{
    				this.treeNodes = new List<TreeNode>();
    			}
    
    			return this.treeNodes;
    		}
    		
    		set
    		{
    			this.treeNodes = value;
    		}
    	}
    }
    
}
