//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behaviour in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
	//------------------------------------------------------------------------------

	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Diagnostics.CodeAnalysis;

	namespace TickBox.Data.Context
{
    [ExcludeFromCodeCoverage]
    public partial class NodeSpecialism
    {
    	public virtual int NodeSpecialismId { get; set; }
    	public virtual int NodeId { get; set; }
    	public virtual int SpecialismId { get; set; }
    	public virtual int SequenceOrder { get; set; }
    	public virtual string Guidelines { get; set; }
    	public virtual string DocumentLink { get; set; }
    	public virtual bool IsScaffold { get; set; }
    
    	public virtual Node Node { get; set; }
    	public virtual Specialism Specialism { get; set; }
    }
    
}
