//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behaviour in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
	//------------------------------------------------------------------------------

	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Diagnostics.CodeAnalysis;

	namespace TickBox.Data.Context
{
    [ExcludeFromCodeCoverage]
    public partial class Specialism
    {
    	public Specialism()
    	{
    	}
    
    	public virtual int SpecialismId { get; set; }
    	public virtual string SpecialismDesc { get; set; }
    	public virtual bool IsScaffold { get; set; }
    
    	private IList<NodeSpecialism> nodeSpecialism;
    	public virtual IList<NodeSpecialism> NodeSpecialism 
    	{ 
    		get
    		{
    			if (this.nodeSpecialism == null)
    			{
    				this.nodeSpecialism = new List<NodeSpecialism>();
    			}
    
    			return this.nodeSpecialism;
    		}
    		
    		set
    		{
    			this.nodeSpecialism = value;
    		}
    	}
    	private IList<Taxonomy> taxonomies;
    	public virtual IList<Taxonomy> Taxonomies 
    	{ 
    		get
    		{
    			if (this.taxonomies == null)
    			{
    				this.taxonomies = new List<Taxonomy>();
    			}
    
    			return this.taxonomies;
    		}
    		
    		set
    		{
    			this.taxonomies = value;
    		}
    	}
    }
    
}
