//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behaviour in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
	//------------------------------------------------------------------------------

	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Diagnostics.CodeAnalysis;

	namespace TickBox.Data.Context
{
    [ExcludeFromCodeCoverage]
    public partial class Taxonomy
    {
    	public Taxonomy()
    	{
    	}
    
    	public virtual int TaxonomyId { get; set; }
    	public virtual int TemplateId { get; set; }
    	public virtual string Title { get; set; }
    	public virtual bool IsScaffold { get; set; }
    
    	public virtual Template Template { get; set; }
    	private IList<TreeNode> treeNodes;
    	public virtual IList<TreeNode> TreeNodes 
    	{ 
    		get
    		{
    			if (this.treeNodes == null)
    			{
    				this.treeNodes = new List<TreeNode>();
    			}
    
    			return this.treeNodes;
    		}
    		
    		set
    		{
    			this.treeNodes = value;
    		}
    	}
    	private IList<Specialism> specialism;
    	public virtual IList<Specialism> Specialism 
    	{ 
    		get
    		{
    			if (this.specialism == null)
    			{
    				this.specialism = new List<Specialism>();
    			}
    
    			return this.specialism;
    		}
    		
    		set
    		{
    			this.specialism = value;
    		}
    	}
    }
    
}
