//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behaviour in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
  //------------------------------------------------------------------------------

  using System.Data;
  using System.Data.Common;
  using System.Data.Entity;
  using System.Data.Entity.Infrastructure;
  using System.Linq;
  using TickBox.Objects;
  
namespace TickBox.Data.Context
{
    public partial class TickBoxEntities : DbContext
    {
      public TickBoxEntities()
        : base("name=TickBoxEntities")
        {
        
    
          }
            
      protected override void OnModelCreating(DbModelBuilder modelBuilder)
      {
          throw new UnintentionalCodeFirstException();
      }
      	public IDbSet<Node> Nodes { get; set; }
    	public IDbSet<NodeSpecialism> NodeSpecialisms { get; set; }
    	public IDbSet<Specialism> Specialisms { get; set; }
    	public IDbSet<Taxonomy> Taxonomies { get; set; }
    	public IDbSet<Template> Templates { get; set; }
    	public IDbSet<TreeNode> TreeNodes { get; set; }
    }
}
