//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behaviour in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics.CodeAnalysis;

namespace TickBox.Objects
{
    public partial class NodeSpecialism : IEquatable<NodeSpecialism>, IKeyComparable<NodeSpecialism>, IScaffold, IEntity
    {
        #region Equality members

        /// <summary>
        /// Indicates whether the current object is equal to another object of the same type.
        /// </summary>
        /// <returns>
        /// true if the current object is equal to the <paramref name="other"/> parameter; otherwise, false.
        /// </returns>
        /// <param name="other">An object to compare with this object.</param>
        public bool Equals(NodeSpecialism other)
        {
            if (ReferenceEquals(null, other))
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return this.NodeSpecialismId == other.NodeSpecialismId
                   && this.NodeId == other.NodeId
                   && this.SpecialismId == other.SpecialismId
                   && this.SequenceOrder == other.SequenceOrder
                   && string.Equals(this.Guidelines, other.Guidelines)
                   && string.Equals(this.DocumentLink, other.DocumentLink)
                   && this.IsScaffold.Equals(other.IsScaffold);
        }

        /// <summary>
        /// The keys match.
        /// </summary>
        /// <param name="other">
        /// The other.
        /// </param>
        /// <returns>
        /// The <see cref="bool"/>.
        /// </returns>
        public bool KeysMatch(NodeSpecialism other)
        {
            if (ReferenceEquals(null, other))
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return this.NodeSpecialismId == other.NodeSpecialismId;
        }

        public int Key {
            get { return this.NodeSpecialismId; }
        }

        /// <summary>
        /// Determines whether the specified <see cref="T:System.Object"/> is equal to the current <see cref="T:System.Object"/>.
        /// </summary>
        /// <returns>
        /// true if the specified <see cref="T:System.Object"/> is equal to the current <see cref="T:System.Object"/>; otherwise, false.
        /// </returns>
        /// <param name="obj">The <see cref="T:System.Object"/> to compare with the current <see cref="T:System.Object"/>. </param>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            if (obj.GetType() != this.GetType())
            {
                return false;
            }

            if (obj.GetType() != this.GetType()) return false;
            return Equals((NodeSpecialism)obj);
        }

        /// <summary>
        /// Serves as a hash function for a particular type. 
        /// </summary>
        /// <returns>
        /// A hash code for the current <see cref="T:System.Object"/>.
        /// </returns>
        public override int GetHashCode()
        {
            unchecked
            {
                var hashCode = this.NodeSpecialismId;
                hashCode = (hashCode * 397) ^ this.NodeId;
                hashCode = (hashCode * 397) ^ this.SpecialismId;
                hashCode = (hashCode * 397) ^ this.SequenceOrder;
                hashCode = (hashCode * 397) ^ (this.Guidelines != null ? this.Guidelines.GetHashCode() : 0);
                hashCode = (hashCode * 397) ^ (this.DocumentLink != null ? this.DocumentLink.GetHashCode() : 0);
                hashCode = (hashCode * 397) ^ this.IsScaffold.GetHashCode();
                return hashCode;
            }
        }

        #endregion
    }

}
