//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behaviour in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
	//------------------------------------------------------------------------------

	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Diagnostics.CodeAnalysis;

	namespace TickBox.Objects
{
    [ExcludeFromCodeCoverage]
    public partial class Template
    {
    	public Template()
    	{
    	}
    
    	public virtual int TemplateId { get; set; }
    	public virtual string Name { get; set; }
    	public virtual string DocumentLink { get; set; }
    	public virtual bool IsScaffold { get; set; }
    
    	private IList<Taxonomy> taxonomies;
    	public virtual IList<Taxonomy> Taxonomies 
    	{ 
    		get
    		{
    			if (this.taxonomies == null)
    			{
    				this.taxonomies = new List<Taxonomy>();
    			}
    
    			return this.taxonomies;
    		}
    		
    		set
    		{
    			this.taxonomies = value;
    		}
    	}
    }
    
}
