//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behaviour in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
	//------------------------------------------------------------------------------

	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Diagnostics.CodeAnalysis;

	namespace TickBox.Objects
{
    [ExcludeFromCodeCoverage]
    public partial class TreeNode
    {
    	public virtual int TaxonomyId { get; set; }
    	public virtual int TreeNodeId { get; set; }
    	public virtual Nullable<int> ParentTreeNodeId { get; set; }
    	public virtual int NodeId { get; set; }
    	public virtual bool IsScaffold { get; set; }
    
    	public virtual Node Node { get; set; }
    	public virtual Taxonomy Taxonomy { get; set; }
    }
    
}
