name: CI
on:
  push:
  - master
  - release-*
  pull_request:
jobs:
  # NUKE eventually
  build:
  # run if our app triggers a build or manually  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2  

      - name: Run a one-line script
        run: 'echo Hello, world!'      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.      
