name: CI
on: [status, workflow_dispatch]  
jobs:
  # NUKE eventually
  build:
  # run if our app triggers a build or manually
    if: (github.event.context == 'AtomReleaseNotes/automated-build') || (github.event.workflow == '.github/workflows/main.yml')
    runs-on: ubuntu-latest
    steps:         
      - name: Trigger Pending Status
        uses: tierconnect/github-actions-statuses@master
        with:
          remotetoken: ${{ secrets.GIT_TOKEN }}
          upstream: ${{ env.UPSTREAM }}
          previousstate: ${{ job.status }}
          init: true

      - name: Checkout
        uses: actions/checkout@v2  

      - name: Run a one-line script
        run: 'echo Hello, world!'      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Trigger Finishing Status
        uses: tierconnect/github-actions-statuses@master
        with:
          remotetoken: ${{ secrets.GIT_TOKEN }}          
          previousstate: ${{ job.status }}
        if: always()
      
